-- Database: sysvoting
CREATE DATABASE sysvoting;

--Após criar o database, executar os scripts abaixo

CREATE SEQUENCE SEQ_TB_VOTING INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
CREATE SEQUENCE SEQ_TB_OPTION INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE TABLE TB_OPTION
(
  id bigint NOT NULL,
  ds_name varchar(500),
  CONSTRAINT PK_TB_OPTION PRIMARY KEY (id)
);

CREATE TABLE TB_VOTING
(
  id bigint NOT NULL,
  DT_VOTING timestamp,
  ID_OPTION bigint,
  CONSTRAINT PK_TB_VOTING PRIMARY KEY (id),
  CONSTRAINT FK_TBOPTION_TBVOTING FOREIGN KEY (ID_OPTION)
      REFERENCES TB_OPTION (id)
);

